
https://www.python.org/dev/peps/pep-3109/

Прямой перехват
    try:
        something()
    except F as V:
        raise F(V)

Указание ошибки
    Ошибка значения
        ValueError(f'ПЕРЕМЕННАЯ value must be ЧЕМ_ДОЛЖЕН_БЫТЬ. {ПЕРЕМЕННАЯ} was passed.')

    Ошибка типа
        TypeError(f'ПЕРЕМЕННАЯ type must be ЧЕМ_ДОЛЖЕН_БЫТЬ. {type(ПЕРЕМЕННАЯ)} was passed.')


ValueError(f'logger value is incorrect: {logger}. Expected bool or None or CommonLoggingClient.')


Валидация

    # ---------------------------------------------------------------------------------------------
    # Преднастройка объекта -----------------------------------------------------------------------
    # ---------------------------------------------------------------------------------------------

    Для функции валидации:
        def __verify....

    Для настройки
        def __control...




https://stackoverflow.com/questions/6062576/adding-information-to-an-exception

Example:

try:
    return [permission() for permission in self.permission_classes]
except TypeError as e:
    raise TypeError("Make sure your view's 'permission_classes' are iterable. "
                    "If you use '()' to generate a set with a single element "
                    "make sure that there is a comma behind the one (element,).") from e

Which looks like this in the end:

2017-09-06 16:50:14,797 [ERROR] django.request: Internal Server Error: /v1/sendEmail/
Traceback (most recent call last):
File "venv/lib/python3.4/site-packages/rest_framework/views.py", line 275, in get_permissions
    return [permission() for permission in self.permission_classes]
TypeError: 'type' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
    # Traceback removed...
TypeError: Make sure your view's Permission_classes are iterable. If
     you use parens () to generate a set with a single element make
     sure that there is a (comma,) behind the one element.